### ISSUE TITLE
KubeJS Thermal breaks Creosote recipes

### ISSUE THREAD

**Issue by Ludi87** [KubeJS-Mods/KubeJS-Thermal#11]
Without KubeJS Thermal, you can burn thermal and immersive engineering creosote in a compression dynamo for RF.
Adding KubeJS Thermal breaks both recipes.

Output from /kubejs warnings:
```
Failed to parse recipe 'thermal:machine/centrifuge/centrifuge_ectoplasm[thermal:centrifuge]': {"item":"cofh_core:ectoplasm"} is not a valid ingredient!
Failed to parse recipe 'thermal:fuels/compression/compression_creosote[thermal:compression_fuel]': {"fluid_tag":"forge:creosote","amount":1000} is not a valid ingredient!
```

MC 1.18.2, Forge 40.1.51
Modlist:

architectury-4.4.71
cofh_core-1.18.2-1.6.3.19
ImmersiveEngineering-1.18.2-8.0.2-149
jei-1.18.2-forge-10.1.0.200
kubejs-forge-1802.5.4-build.492
kubejs-thermal-1802.1.5-build.12
rhino-forge-1802.1.14-build.182
thermal_cultivation-1.18.2-1.6.1.9
thermal_expansion-1.18.2-1.6.1.11
thermal_foundation-1.18.2-1.6.2.27
thermal_innovation-1.18.2-1.6.1.10
thermal_locomotion-1.18.2-1.6.0.6

Logs:
https://pste.ch/akanoqacal.pl

**Comment by KingLemming** [comment]
Seems to be a pretty easy fix from what I can tell - FuelRecipe needs the same logic as BasicThermalRecipe as far as fluids go.
