### ISSUE TITLE
Fluid Encapsulator documentation?

### ISSUE THREAD

**Issue by github-fave** [KubeJS-Mods/KubeJS-Thermal#13]
Hi, I'd like to add a recipe to the Fluid Encapsulator, but I have no clue how to. Could you help me?

**Comment by ChiefArug** [comment]
This is now documented on this wiki page: https://mods.latvian.dev/books/kubejs/page/kubejs-thermal
If you need further help the discord is a much better place to ask: https://discord.gg/bPFfH6P
