### ISSUE TITLE
Error with adding an Induction Smelter recipe on a Dedicated Server

### ISSUE THREAD

**Issue by Firestar311** [KubeJS-Mods/KubeJS-Thermal#16]
This worked on single player, but I had an error when trying to connect to a multiplayer server with the script below
`ServerEvents.recipes(event => {
	event.remove({output: 'create:cinder_flour', type: 'thermal:pulverizer'})
	event.remove({output: 'mekanism:steel_casing'});
	event.recipes.thermal.smelter('mekanism:steel_casing', ['4x thermal:steel_ingot', '#forge:glass', 'mekanism:ingot_osmium']).energy(10000);
})`
Then when I changed the recipe to `event.recipes.thermal.smelter('mekanism:steel_casing', ['thermal:steel_block', '#forge:glass', 'mekanism:ingot_osmium']).energy(10000);` it was fine
The error was as follows `Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class cofh.lib.util.crafting.IngredientWithCount cannot be cast to class dev.latvian.mods.kubejs.platform.forge.ingredient.KubeJSIngredient (cofh.lib.util.crafting.IngredientWithCount is in module cofh_core@10.2.1 of loader 'TRANSFORMER' @cd5ff55; dev.latvian.mods.kubejs.platform.forge.ingredient.KubeJSIngredient is in module kubejs@1902.6.0-build.142 of loader 'TRANSFORMER' @cd5ff55)`

**Comment by MaxNeedsSnacks** [comment]
Known issue on CoFHCore's end, please update your mods

**Comment by MaxNeedsSnacks** [comment]
Nevermind the update part, I don't think Lemming has released a new version yet... ugh
