### ISSUE TITLE
Fuel refinery documentation?

### ISSUE THREAD

**Issue by SigmaFlame** [KubeJS-Mods/KubeJS-Thermal#7]
Hello, I want to transform refined fuel to fuelium (mycrayfish vehicle). How to do that please?

**Comment by MaxNeedsSnacks** [comment]
The format for *most* thermal recipes is the same, so it should be as simple as
```js
onEvent('recipes', e => {
  e.thermalRefinery([Fluid.of("idkwhatmodid:fuelium", 1000)],[Fluid.of("thermal:refined_fuel", 1500)])
})
```
